version: 0.2

env:
  variables:
    spring.profiles.active: "aws"

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Started at `date`
      - ./gradlew build
artifacts:
  files:
    - build/libs/restapi-0.0.1-SNAPSHOT.jar