version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build Started at `date`
      - gradlew build
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'